backend:
  name: git-gateway
  branch: gh-pages
media_folder: 'assets/uploads'

collections:
  - name: 'recipe'
    label: 'מתכון'
    folder: '_posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {label: "תאריך פרסום", name: "date", widget: "datetime"}
      - {label: 'כותרת', name: 'title', widget: 'string'}
      - {label: "תמונת נושא", name: "featured_image", widget: "image"}
      - {label: "המתכון", name: "body", widget: "markdown"}
      - label: "קטגוריות"
        name: "categories"
        widget: "list"
        field: {label: 'קטגוריה', name: 'category', widget: 'string'}
